In [1]:
import numpy as np

import matplotlib
from matplotlib import pyplot as plt

from IPython.display import HTML
from IPython.display import display

from skeleton_models import ntu_rgbd, get_kernel_by_group, ntu_ss_1, ntu_ss_2, ntu_ss_3, partial

from zoo_pose_embedding import TwoLayersGCNPoseEmbedding
from zoo_action_encoder_units import TransformerEncoderUnit
from zoo_action_decoder_units import TransformerDecoderUnit
from zoo_upsampling import StepByStepUpsampling, JoaosUpsampling

from model import ActionEmbeddingTransformer
from layers import subsequent_mask

from render import animate
import math, copy, time
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

import os, glob

In [2]:
sample_data = np.load('../datasets/NTURGB-D/Python/raw_npy/S003C001P008R002A023.skeleton.npy', allow_pickle=True)[()]

In [3]:
# Um equeleto com 5 vertices
A = np.array([
[ 1, 1, 1, 1, 1],
[ 1, 1, 0, 0, 0],
[ 1, 0, 1, 0, 0],
[ 1, 0, 0, 1, 0],
[ 1, 0, 0, 0, 1],
    ])
print(A)
print(A.shape)

[[1 1 1 1 1]
 [1 1 0 0 0]
 [1 0 1 0 0]
 [1 0 0 1 0]
 [1 0 0 0 1]]
(5, 5)


In [4]:
# Uma matriz de adjacencias de multigrafo tamanho 2
Am = np.stack((A,A))
print(Am)
print(Am.shape) # K, V, V

[[[1 1 1 1 1]
  [1 1 0 0 0]
  [1 0 1 0 0]
  [1 0 0 1 0]
  [1 0 0 0 1]]

 [[1 1 1 1 1]
  [1 1 0 0 0]
  [1 0 1 0 0]
  [1 0 0 1 0]
  [1 0 0 0 1]]]
(2, 5, 5)


In [5]:
# Uma pose com vertices no espaço 2D
X = np.array([
    [0, 0],
    [1, 1],
    [-2, 1],
    [1, -1],
    [-1, -2]
])
print(X)
print(X.shape) 

[[ 0  0]
 [ 1  1]
 [-2  1]
 [ 1 -1]
 [-1 -2]]
(5, 2)


In [6]:
# Um grupo de 7 poses
Xm = np.stack((X,X,X,X,X,X,X))
# print(Xm)
print(Xm.shape) # N, V, C

(7, 5, 2)


In [7]:
# Um grupo (7 amostras) de sequencias temporais (3 instantes) de poses
Xmt = np.stack((Xm, Xm, Xm), axis=1)
Xmt.shape

(7, 3, 5, 2)

In [8]:
# Converte para tensor

Ain = torch.from_numpy(Am).float()
print(Ain.size())

Xin = torch.from_numpy(Xmt).float()
print(Xin.size())


torch.Size([2, 5, 5])
torch.Size([7, 3, 5, 2])


In [9]:
conf_kernel_size = 2
conf_num_nodes = 5
conf_heads = 1
conf_encoding_per_node = 20
conf_internal_per_node = int(conf_encoding_per_node/conf_heads)

class BetterThatBestModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = ActionEmbeddingTransformer(
            TwoLayersGCNPoseEmbedding(
                2,
                conf_encoding_per_node,
                conf_kernel_size,
                num_nodes = conf_num_nodes
            ),
            TransformerEncoderUnit (
                heads=conf_heads,
                embedding_in=conf_num_nodes*conf_encoding_per_node,
                embedding_out=conf_num_nodes*conf_internal_per_node
            ),
            TransformerDecoderUnit(
                heads=conf_heads,
                embedding_in=conf_num_nodes*conf_encoding_per_node,
                embedding_out=conf_num_nodes*conf_internal_per_node,
                memory_in=conf_num_nodes*conf_encoding_per_node
            ),

            JoaosUpsampling(
                conf_num_nodes,
                conf_encoding_per_node*conf_num_nodes,
                node_channel_out = 2
            )
        )

    def forward(self, x_in, x_out, A, mask):
        return self.model(x_in, x_out, A, mask)

In [10]:
a = BetterThatBestModel()
out = a(Xin, Xin, Ain, subsequent_mask(3))
print(out.size())

torch.Size([7, 3, 100])
torch.Size([7, 3, 100])
torch.Size([7, 3, 25, 2])


In [11]:
Xin.size()

torch.Size([7, 3, 5, 2])

In [12]:
A = 3
B = 4
C = 5
D = 6
teste = torch.zeros( (A,B,C,D) ) 

for a in range(3):
    for b in range(4):
        for c in range(5):
            for d in range(6):
                teste[a,b,c,d] = a + 10*b + 100*c + 1000*d

teste[0,:,:,0] 

tensor([[  0., 100., 200., 300., 400.],
        [ 10., 110., 210., 310., 410.],
        [ 20., 120., 220., 320., 420.],
        [ 30., 130., 230., 330., 430.]])

In [13]:
t = teste.permute(0,3,2,1) # [A,B,C,D] -> [A, D, C, B]
print(t[0,:,:,0])
t = t.contiguous().view(A, D*C, B)
print(t[0,:,0])
t = t.contiguous().view(A, D, C*B)
print(t[0,:,0])
t = t.permute(0,2,1) # [A,D,C*B] -> [A,C*B,D]
print(t[0,:,0])
t = t.contiguous().view(A, C, B*D)
print(t[0,:,0])
t = t.permute(0,2,1) # [A,C,B*D] -> [A,B*D,C]
print(t[0,:,0])
t = t.contiguous().view(A, B, D, C)
print(t[0,:,0, 0])
t = t.permute(0,1,3,2) # [A,B,D,C] -> [A,B,C,D]
print(t[0,:,:,0])

tensor([[   0.,  100.,  200.,  300.,  400.],
        [1000., 1100., 1200., 1300., 1400.],
        [2000., 2100., 2200., 2300., 2400.],
        [3000., 3100., 3200., 3300., 3400.],
        [4000., 4100., 4200., 4300., 4400.],
        [5000., 5100., 5200., 5300., 5400.]])
tensor([   0.,  100.,  200.,  300.,  400., 1000., 1100., 1200., 1300., 1400.,
        2000., 2100., 2200., 2300., 2400., 3000., 3100., 3200., 3300., 3400.,
        4000., 4100., 4200., 4300., 4400., 5000., 5100., 5200., 5300., 5400.])
tensor([   0., 1000., 2000., 3000., 4000., 5000.])
tensor([  0.,  10.,  20.,  30., 100., 110., 120., 130., 200., 210., 220., 230.,
        300., 310., 320., 330., 400., 410., 420., 430.])
tensor([  0., 100., 200., 300., 400.])
tensor([   0., 1000., 2000., 3000., 4000., 5000.,   10., 1010., 2010., 3010.,
        4010., 5010.,   20., 1020., 2020., 3020., 4020., 5020.,   30., 1030.,
        2030., 3030., 4030., 5030.])
tensor([ 0., 10., 20., 30.])
tensor([[  0., 100., 200., 300., 400.],
     

In [14]:
def calculate_params(heads, num_nodes, scale_factor):
    channel_out = scale_factor*num_nodes
    channel_in = heads * channel_out
    return channel_in, channel_out

In [15]:
calculate_params(8, 25, 4)

(800, 100)